# Generated by Django 6.0.1 on 2026-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('labels', '0002_remove_label_label_type_remove_labeltype_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='label',
        ),
        migrations.AddField(
            model_name='job',
            name='labels',
            field=models.ManyToManyField(related_name='jobs', to='labels.label'),
        ),
    ]
