# Generated by Django 6.0.1 on 2026-02-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_label_job_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='barcode',
            field=models.CharField(default='5038135000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='jobs.customer'),
        ),
    ]
