# Generated by Django 6.0.1 on 2026-02-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportparameter',
            name='parameter_type',
            field=models.CharField(choices=[('date', 'Date'), ('int', 'Integer'), ('str', 'String'), ('choice', 'Choice'), ('bool', 'Boolean')], help_text='Parameter type', max_length=10),
        ),
    ]
