# Generated by Django 6.0.1 on 2026-02-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportparameter_parameter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportparameter',
            name='source_model',
            field=models.CharField(blank=True, help_text='app_label.ModelName for choice parameters(optional) ', max_length=50, null=True),
        ),
    ]
