# Generated by Django 6.0.1 on 2026-01-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colourman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('colourman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colourman.colourman')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.label')),
                ('label_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.labeltype')),
                ('lass_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.labelsize')),
            ],
        ),
    ]
