# Generated by Django 6.0.1 on 2026-01-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0002_rename_lass_size_printinglog_label_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unacceptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colourman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colourman.colourman')),
            ],
        ),
    ]
