# Generated by Django 6.0.1 on 2026-02-13 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0004_printinglog_usage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinglog',
            name='usage_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
