# Generated by Django 6.0.1 on 2026-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0005_alter_printinglog_usage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unacceptable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='printinglog',
            name='usage_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
