# Generated by Django 6.0.1 on 2026-02-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0006_unacceptable_updated_at_alter_printinglog_usage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printinglog',
            name='label_size',
        ),
        migrations.RemoveField(
            model_name='printinglog',
            name='label_type',
        ),
    ]
