# Generated by Django 6.0.1 on 2026-02-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0007_remove_printinglog_label_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourman',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
