# Generated by Django 6.0.1 on 2026-02-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0008_colourman_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacceptable',
            name='colourman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fails', to='colourman.colourman'),
        ),
    ]
