# Generated by Django 6.0.1 on 2026-02-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0009_alter_unacceptable_colourman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unacceptable',
            name='colourman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unacceptable', to='colourman.colourman'),
        ),
    ]
