# Generated by Django 6.0.1 on 2026-02-17 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0010_alter_unacceptable_colourman'),
        ('jobs', '0004_job_is_active'),
        ('labels', '0005_alter_label_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinglog',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_usage_log_jobs', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='printinglog',
            name='colourman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_usage_log_colourman', to='colourman.colourman'),
        ),
        migrations.AlterField(
            model_name='printinglog',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_usage_log_label', to='labels.label'),
        ),
    ]
