# Generated by Django 6.0.1 on 2026-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0011_alter_printinglog_code_alter_printinglog_colourman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unacceptable',
            name='for_investigation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unacceptable',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=2),
        ),
    ]
