# Generated by Django 6.0.1 on 2026-02-19 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0012_unacceptable_for_investigation_unacceptable_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colourman',
            options={'ordering': ['clock_number']},
        ),
        migrations.AlterField(
            model_name='unacceptable',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
