# Generated by Django 6.0.1 on 2026-02-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0013_alter_colourman_options_alter_unacceptable_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colourman',
            options={'ordering': ['pk']},
        ),
    ]
