# Generated by Django 6.0.1 on 2026-02-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0014_alter_colourman_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colourman',
            options={'ordering': ['clock_number']},
        ),
    ]
