# Generated by Django 6.0.1 on 2026-02-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0015_alter_colourman_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourman',
            name='clock_number',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
