# Generated by Django 6.0.1 on 2026-02-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0016_alter_colourman_clock_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colourman',
            name='clock_number',
            field=models.IntegerField(unique=True),
        ),
    ]
