# Generated by Django 6.0.1 on 2026-02-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colourman', '0017_alter_colourman_clock_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colourman',
            options={},
        ),
    ]
