# Generated by Django 6.0.1 on 2026-01-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('usage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LabelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_preprinted', models.BooleanField(default=False)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_types', to='labels.labelsize')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image_location', models.CharField(blank=True, max_length=100, null=True)),
                ('label_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='labels.labeltype')),
            ],
        ),
    ]
