# Generated by Django 6.0.1 on 2026-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='label_type',
        ),
        migrations.RemoveField(
            model_name='labeltype',
            name='size',
        ),
        migrations.AddField(
            model_name='label',
            name='label_types',
            field=models.ManyToManyField(related_name='labels', to='labels.labeltype'),
        ),
        migrations.AddField(
            model_name='labeltype',
            name='sizes',
            field=models.ManyToManyField(related_name='label_types', to='labels.labelsize'),
        ),
    ]
