# Generated by Django 6.0.1 on 2026-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_label_label_type_remove_labeltype_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='image_location',
        ),
        migrations.AddField(
            model_name='label',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
