# Generated by Django 6.0.1 on 2026-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_remove_label_image_location_label_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='bar_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
