# Generated by Django 6.0.1 on 2026-02-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_label_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='bar_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
